#!/bin/bash

echo "=========================================="
echo "Tree Builder App - GitHub Setup Guide"
echo "=========================================="
echo ""
echo "Follow these steps to push your app to GitHub:"
echo ""
echo "1. Create a new repository on GitHub:"
echo "   - Go to https://github.com/new"
echo "   - Name: tree-builder-app (or your preferred name)"
echo "   - Make it Public or Private"
echo "   - DO NOT initialize with README, .gitignore, or license"
echo "   - Click 'Create repository'"
echo ""
echo "2. In this directory, run these commands:"
echo ""
echo "   cd /home/claude/tree-builder-app"
echo "   git init"
echo "   git add ."
echo "   git commit -m 'Initial commit: Hierarchical Tree Builder'"
echo "   git branch -M main"
echo "   git remote add origin https://github.com/YOUR_USERNAME/tree-builder-app.git"
echo "   git push -u origin main"
echo ""
echo "   (Replace YOUR_USERNAME with your GitHub username)"
echo ""
echo "3. Deploy to Vercel:"
echo "   - Go to https://vercel.com"
echo "   - Sign in with GitHub"
echo "   - Click 'Add New Project'"
echo "   - Import your tree-builder-app repository"
echo "   - Click 'Deploy'"
echo ""
echo "   Vercel will automatically detect Next.js and deploy!"
echo ""
echo "=========================================="
echo "Your project is ready in: /home/claude/tree-builder-app"
echo "=========================================="
